function kw = model_keyword()
% no input
% this function returns the keyword for the ampl model check

% Version 1.0 : Lu, Hong
% Email: hlu39@sheffield.ac.uk
% Last Modified: July 24, 2021

    kw = {'n_ts',...
          'dt',...
          'n_agent',...
          'n_obs',...
          'n_wp',...
          'waypoints',...
          'obs_centroid',...
          'obs_radius',...
          'obs_inflation',...
          'n_vel_cst',...
          'n_acc_cst',...
          'n_obs_cst',...
          'acc_max',...
          'vel_max',...
          'vel_min',...
          'pos_init',...
          'vel_init',...
          'pos_final',...
          'pos_cst',...
          'cos_vel',...
          'sin_vel',...
          'cos_acc',...
          'sin_acc',...
          'cos_obs',...
          'sin_obs',...
          'cos_vmax',...
          'cos_amax',...
          'epsilon'};
end